In [ ]:
!git clone https://github.com/arishhasan192/data.git

Cloning into 'data'...
remote: Enumerating objects: 1311, done.
remote: Counting objects: 100% (1311/1311), done.
remote: Compressing objects: 100% (1308/1308), done.
remote: Total 1311 (delta 1), reused 1311 (delta 1), pack-reused 0
Receiving objects: 100% (1311/1311), 19.88 MiB | 30.08 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [ ]:
cd data/

/content/data


In [ ]:
import cv2

# store list
images = []
lables = []

## AD Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 172):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final AD JPEG/AD ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(0)  # AD

In [ ]:
## CN Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 581):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final CN JPEG/CN ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(1)  # CN
     

In [ ]:
## EMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 241):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final EMCI JPEG/EMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(2)  # EMCI
     


In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 73):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final LMCI JPEG/LMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(3)  # LMCI
     

In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 234):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final MCI JPEG/MCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(4)  # MCI

In [ ]:
# Shape of the Images

print(f"Shape of each image is = {images[1000].shape}")

Shape of each image is = (200, 200)


In [ ]:

# Convert The List into Array Format  #

import numpy as np

train_feature = np.array(images)
lables = np.array(lables)
     


In [ ]:
## Display Array Shape ##

print(f"image dataset shape = {train_feature.shape}")

print(f"lable dataset shape = {lables.shape}")

image dataset shape = (1296, 200, 200)
lable dataset shape = (1296,)


In [ ]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_target, test_target = train_test_split(train_feature,lables,test_size=0.2)

print(f"train_features shape = {train_features.shape}")

print(f"test_features shape = {test_features.shape}")

print(f"train_target shape = {train_target.shape}")

print(f"test_target shape = {test_target.shape}")

train_features shape = (1036, 200, 200)
test_features shape = (260, 200, 200)
train_target shape = (1036,)
test_target shape = (260,)


In [ ]:
import keras
import tensorflow
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM, Dropout

# ONE NOT ENCODING
train_target = to_categorical(lables)

# MODEL LAYERS
model = Sequential()
model.add(SimpleRNN(256, input_shape=(200, 200)))
model.add(Dropout(0.2))
model.add(Dense(50, activation='relu'))
model.add(Dense(5, activation='softmax'))
model.summary()


Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_12 (SimpleRNN)   (None, 256)               116992    
                                                                 
 dropout_9 (Dropout)         (None, 256)               0         
                                                                 
 dense_11 (Dense)            (None, 50)                12850     
                                                                 
 dense_12 (Dense)            (None, 5)                 255       
                                                                 
Total params: 130,097
Trainable params: 130,097
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# MODEL COPILE

from tensorflow.keras.optimizers import Adam

model.compile(Adam(learning_rate = 0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(train_feature, train_target, batch_size = 30, epochs = 20)

Epoch 1/20
44/44 [==============================] - 9s 185ms/step - loss: 1.4870 - accuracy: 0.4020
Epoch 2/20
44/44 [==============================] - 9s 192ms/step - loss: 1.4568 - accuracy: 0.4275
Epoch 3/20
44/44 [==============================] - 9s 205ms/step - loss: 1.4372 - accuracy: 0.4437
Epoch 4/20
44/44 [==============================] - 8s 185ms/step - loss: 1.4312 - accuracy: 0.4460
Epoch 5/20
44/44 [==============================] - 8s 190ms/step - loss: 1.4278 - accuracy: 0.4460
Epoch 6/20
44/44 [==============================] - 9s 203ms/step - loss: 1.4301 - accuracy: 0.4483
Epoch 7/20
44/44 [==============================] - 8s 188ms/step - loss: 1.4133 - accuracy: 0.4491
Epoch 8/20
44/44 [==============================] - 8s 187ms/step - loss: 1.4095 - accuracy: 0.4452
Epoch 9/20
44/44 [==============================] - 9s 203ms/step - loss: 1.4070 - accuracy: 0.4452
Epoch 10/20
44/44 [==============================] - 8s 192ms/step - loss: 1.4160 - accuracy: 0.4429

In [ ]:
prediction = model.predict(test_features)


9/9 [==============================] - 1s 47ms/step


In [ ]:
# Accuracy of Our Model #
import numpy as np
from keras.models import load_model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_true = []
y_pred = []
for i in range(260) :

    predicted_label = np.argmax(prediction[i])
    y_true.append(test_target[i])
    y_pred.append(predicted_label)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
confusion = confusion_matrix(y_true, y_pred)
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1)
print('Confusion Matrix:\n', confusion)
     

Accuracy: 0.4807692307692308
Precision: 0.3016238197365123
Recall: 0.27298706827736685
F1 Score: 0.24789376356644416
Confusion Matrix:
 [[  0  36   3   0   2]
 [  0 105   4   0   5]
 [  0  31  14   0   1]
 [  0  15   1   0   0]
 [  0  36   1   0   6]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
