In [ ]:
!git clone https://github.com/arishhasan192/data.git

Cloning into 'data'...
remote: Enumerating objects: 1311, done.
remote: Counting objects: 100% (1311/1311), done.
remote: Compressing objects: 100% (1308/1308), done.
remote: Total 1311 (delta 1), reused 1311 (delta 1), pack-reused 0
Receiving objects: 100% (1311/1311), 19.88 MiB | 21.68 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [ ]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

In [ ]:
cd data/

/content/data


In [ ]:
import cv2

# store list
images = []
lables = []

## AD Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 172):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final AD JPEG/AD ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(0)  # AD

In [ ]:
## CN Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 581):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final CN JPEG/CN ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(1)  # CN
     

In [ ]:
## EMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 241):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final EMCI JPEG/EMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(2)  # EMCI
     


In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 73):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final LMCI JPEG/LMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(3)  # LMCI
     

In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 234):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final MCI JPEG/MCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(4)  # MCI

In [ ]:

# Convert The List into Array Format  #

import numpy as np

train_feature = np.array(images)
lables = np.array(lables)
     


In [ ]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_target, test_target = train_test_split(train_feature,lables,test_size=0.12)

print(f"train_features shape = {train_features.shape}")

print(f"test_features shape = {test_features.shape}")

print(f"train_target shape = {train_target.shape}")

print(f"test_target shape = {test_target.shape}")

train_features shape = (1140, 200, 200)
test_features shape = (156, 200, 200)
train_target shape = (1140,)
test_target shape = (156,)


In [ ]:
import keras
import tensorflow
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout, Reshape, LSTM

# ONE NOT ENCODING

train_target = to_categorical(lables)

# MODEL LAYERS

model = Sequential()
# Convolutional Layers
model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu', input_shape=(200, 200, 1)))

model.add(Conv2D(75, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Reshape((-1, model.output_shape[-1]))) # Reshape the output of the Flatten layer to have a time dimension

model.add(LSTM(64, return_sequences=False))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(25, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 200, 200, 25)      250       
                                                                 
 conv2d_1 (Conv2D)           (None, 200, 200, 75)      16950     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 100, 100, 75)     0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 750000)            0         
                                                                 
 reshape (Reshape)           (None, 1, 750000)         0         
                                                                 
 lstm (LSTM)                 (None, 64)                192016640 
                                                        

In [ ]:
# MODEL COPILE

from tensorflow.keras.optimizers import Adam

model.compile(Adam(learning_rate = 0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(train_feature, train_target, batch_size = 30, epochs = 15)

Epoch 1/15
44/44 [==============================] - 22s 166ms/step - loss: 1.4470 - accuracy: 0.4383
Epoch 2/15
44/44 [==============================] - 7s 154ms/step - loss: 1.4280 - accuracy: 0.4475
Epoch 3/15
44/44 [==============================] - 7s 155ms/step - loss: 1.4222 - accuracy: 0.4475
Epoch 4/15
44/44 [==============================] - 7s 155ms/step - loss: 1.4215 - accuracy: 0.4475
Epoch 5/15
44/44 [==============================] - 7s 155ms/step - loss: 1.4215 - accuracy: 0.4475
Epoch 6/15
44/44 [==============================] - 7s 156ms/step - loss: 1.4182 - accuracy: 0.4475
Epoch 7/15
44/44 [==============================] - 7s 156ms/step - loss: 1.4247 - accuracy: 0.4475
Epoch 8/15
44/44 [==============================] - 7s 158ms/step - loss: 1.4178 - accuracy: 0.4475
Epoch 9/15
44/44 [==============================] - 7s 157ms/step - loss: 1.4182 - accuracy: 0.4475
Epoch 10/15
44/44 [==============================] - 7s 159ms/step - loss: 1.4207 - accuracy: 0.447

In [ ]:
predictions = model.predict(test_features)


5/5 [==============================] - 1s 135ms/step


In [ ]:
# Accuracy of Our Model #
import numpy as np
from keras.models import load_model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_true = []
y_pred = []
for i in range(156) :

    predicted_label = np.argmax(predictions[i])
    y_true.append(test_target[i])
    y_pred.append(predicted_label)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
confusion = confusion_matrix(y_true, y_pred)
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1)
print('Confusion Matrix:\n', confusion)
     

Accuracy: 0.46153846153846156
Precision: 0.09230769230769231
Recall: 0.2
F1 Score: 0.12631578947368421
Confusion Matrix:
 [[ 0 19  0  0  0]
 [ 0 72  0  0  0]
 [ 0 32  0  0  0]
 [ 0 10  0  0  0]
 [ 0 23  0  0  0]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
