In [ ]:
!dir

sample_data


In [ ]:
!git clone https://github.com/arishhasan192/data.git

Cloning into 'data'...
remote: Enumerating objects: 1311, done.
remote: Counting objects: 100% (1311/1311), done.
remote: Compressing objects: 100% (1308/1308), done.
remote: Total 1311 (delta 1), reused 1311 (delta 1), pack-reused 0
Receiving objects: 100% (1311/1311), 19.88 MiB | 17.77 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [ ]:
cd data/

/content/data


In [ ]:
!ls

Alzheimers-ADNI  Images  README.md


In [ ]:
import cv2

# store list
images = []
lables = []

## AD Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 172):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final AD JPEG/AD ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(0)  # AD

In [ ]:
## CN Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 581):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final CN JPEG/CN ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(1)  # CN
     

In [ ]:
## EMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 241):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final EMCI JPEG/EMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(2)  # EMCI
     


In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 73):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final LMCI JPEG/LMCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(3)  # LMCI
     

In [ ]:
## LMCI Patient Brain Scan with PreProcessing of the Image ##
for i in range(1, 234):
    img = cv2.imread(f"/content/data/Alzheimers-ADNI/train/Final MCI JPEG/MCI ({i}).jpg")
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray = gray/255
    gray = cv2.resize(gray,(200, 200))
    images.append(gray)
    lables.append(4)  # MCI

In [ ]:
# Shape of the Images

print(f"Shape of each image is = {images[1000].shape}")

Shape of each image is = (200, 200)


In [ ]:

# Convert The List into Array Format  #

import numpy as np

train_feature = np.array(images)
lables = np.array(lables)
     


In [ ]:
## Display Array Shape ##

print(f"image dataset shape = {train_feature.shape}")

print(f"lable dataset shape = {lables.shape}")

image dataset shape = (1296, 200, 200)
lable dataset shape = (1296,)


In [ ]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_target, test_target = train_test_split(train_feature,lables,test_size=0.2)

print(f"train_features shape = {train_features.shape}")

print(f"test_features shape = {test_features.shape}")

print(f"train_target shape = {train_target.shape}")

print(f"test_target shape = {test_target.shape}")

train_features shape = (1036, 200, 200)
test_features shape = (260, 200, 200)
train_target shape = (1036,)
test_target shape = (260,)


In [ ]:
# MODEL ARCHITECTURE

import keras
import tensorflow
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout

# ONE NOT ENCODING

train_target = to_categorical(lables)

# MODEL LAYERS

model=Sequential()
# Convolutional Layers
model.add(Conv2D(32, kernel_size = (3,3), str  ides = (1,1), input_shape = (200, 200, 1)))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(64, kernel_size = (3,3), strides = (1,1), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(25,activation='relu'))
model.add(Dense(5,activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_15 (Conv2D)          (None, 198, 198, 32)      320       
                                                                 
 max_pooling2d_12 (MaxPoolin  (None, 99, 99, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_16 (Conv2D)          (None, 97, 97, 64)        18496     
                                                                 
 max_pooling2d_13 (MaxPoolin  (None, 48, 48, 64)       0         
 g2D)                                                            
                                                                 
 conv2d_17 (Conv2D)          (None, 46, 46, 128)       73856     
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 23, 23, 128)     

In [ ]:
# MODEL COPILE

from tensorflow.keras.optimizers import Adam

model.compile(Adam(learning_rate = 0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(train_feature, train_target, batch_size = 30, epochs = 20)

Epoch 1/20
44/44 [==============================] - 3s 33ms/step - loss: 1.4541 - accuracy: 0.4475
Epoch 2/20
44/44 [==============================] - 1s 31ms/step - loss: 1.4096 - accuracy: 0.4475
Epoch 3/20
44/44 [==============================] - 1s 32ms/step - loss: 1.4131 - accuracy: 0.4475
Epoch 4/20
44/44 [==============================] - 1s 32ms/step - loss: 1.3939 - accuracy: 0.4483
Epoch 5/20
44/44 [==============================] - 1s 32ms/step - loss: 1.3622 - accuracy: 0.4514
Epoch 6/20
44/44 [==============================] - 1s 31ms/step - loss: 1.3263 - accuracy: 0.4606
Epoch 7/20
44/44 [==============================] - 1s 32ms/step - loss: 1.2783 - accuracy: 0.4722
Epoch 8/20
44/44 [==============================] - 1s 32ms/step - loss: 1.1785 - accuracy: 0.5085
Epoch 9/20
44/44 [==============================] - 1s 31ms/step - loss: 1.0791 - accuracy: 0.5255
Epoch 10/20
44/44 [==============================] - 1s 31ms/step - loss: 0.9862 - accuracy: 0.5710
Epoch 11/

In [ ]:
prediction = model.predict(test_features)


9/9 [==============================] - 0s 14ms/step


In [ ]:
# Accuracy of Our Model #
import numpy as np
from keras.models import load_model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_true = []
y_pred = []
for i in range(260) :
    predicted_label = np.argmax(prediction[i])
    y_true.append(test_target[i])
    y_pred.append(predicted_label)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
confusion = confusion_matrix(y_true, y_pred)
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1)
print('Confusion Matrix:\n', confusion)
     

Accuracy: 0.9346153846153846
Precision: 0.9071778085014095
Recall: 0.8438664110584199
F1 Score: 0.8478546286905523
Confusion Matrix:
 [[ 27   0   0   0   0]
 [  0 108   2   0   0]
 [  2   0  50   1   0]
 [  0   0   1   5  11]
 [  0   0   0   0  53]]
